[[protobuf_c]]
arch = "aarch64"
git-tree-sha1 = "443c386052910f3884ecd875bf7bba5527314bdb"
os = "macos"

    [[protobuf_c.download]]
    sha256 = "cfd1ad6cda857b98d609fe4ed590d2ada0d487fd54b6a4468e1bf45413339a18"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.aarch64-apple-darwin.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a885dc5a4cdd5cf8a7079396d96fc8fa07b48afb"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "c26acee2154fbcafa8cbdfcc33ac008c9b2db0a223aec2d9a0573ec9c6ad3460"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb198aec164d936122d2ad1f0521d4e9b4dc50ee"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "4362853df90145805fe23b85391afc1efb70655c2ff75e60d25b71ca6bdd5972"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57560c72152522a9c767eba0fbe98a1981d3902d"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "945cd0e757d1047a4280c09fc5cbd2693b557be4da4fcf9047483439617c573a"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "315efde46d5e0906da738cf88da7875ce263086d"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "d1008b9db645c754213581d394146b442bf013bba444fa9e95f557da26022db2"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fb8ded0eae69deb7c2470d210cb26d71c11d69a"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "80b43eb2126f7fddc1ec100b157729c93f16897985002c07774180f9f4f99406"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d302ffcd3f35ff6baced8c7e9d841f69220cb761"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "3b3f239f2111e6b0d303bb06fc5e4accae346ca63a469a5a935dc04667e6ccd1"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3596c7b9959232056e61ccc11b2daeeebffd238f"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "b4bf5cf7486ddd5dee202d27f442dab622086449170a2814afb98f2aee74c4f9"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ee50f4b5fd1cd0032586588ee246022b5485be3"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "233452e8fc62310b139ad0c5af4a3ba0e88ffe21a44cb6db648ee2c848674f39"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "422f6c0a7d3c96356cc400f090a596496a6204ab"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "ebd982a17fd9f7db5b96bb96a8e2a0ff2b156eed37289c74f8cfd9b7d7eeb14b"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b85ad427d4c5c37cd1b43963203ebf10384b411"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "919f8d262ec9b5496044fbde99d7f98c3a109ba89fdb3cbb9263a0ecf06e8132"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de305dc5fce0070dc896583c29b813cb9a4bb33"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "e4185733a22d5aa7f1fa31bdcbf498c9aee47144a3a08e3fcc875ba739329b7c"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1203c40b596bfd6aebd65782f29b8635b37ec61"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "45a9932421b871bcb50b692f5ae61d25d3c1abaed007e94997f0589ab9772e09"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0db7aa2cd2dda6d4bc414f05c8a36670252ffd8a"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "95caf880cc0f70c2c5b6fd0b78eeb0c327bd79ccba90cc429d7a6917b8e427d8"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1536bb1cf7bcbf2a9d265e1da0ee04be5c19ca18"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "814afcd6465fbb8e62b0ebee031ccc26011834821643ec2013595641a0769e02"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71897c8fa0f5c1e0b12bb5ffc97965b594b98e8e"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "5afcec12f21349f63970b2b16a1d3bbeb9b63ee6ada62322ebac0e1ff30b6cc6"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fedbbf4bcd8eb1abd6284ed9cda55caacd262a9c"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "d3ee3514ae8ab7b35a986e138c7a484a4973f0224e622aad512450841517ce89"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0b8991d1f55688b86e10a4783cdaabe0f82b6ac"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "d78fd707e8b7ac5b129caed493656824ecf29c87767393d7609eb1785145294b"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33284380ad7b7ee27a3cabe3a1fae6b6ed984714"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "36675f185f1f5bd0a80d30dc9d09d7963073912e0b2cc151e3efa58da76d540e"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[protobuf_c]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fee0ef2e3b847f96ec167b022601a2c3ef1783ef"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "e9de7b30e6ef7c2bd49e55d9b4554e274f192e9c59951e738906617f6d5be662"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ffe24be85a6030ac2d0ec7d61335b803c74e4a4"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "0df55304c8cc93b0fd89bb80a8bbd86e16e506bde624f6305130aff452f1b608"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
git-tree-sha1 = "810f2db13858f42185d0a449ecad3f9c01d19265"
os = "macos"

    [[protobuf_c.download]]
    sha256 = "e7fd190829580838047b6a122ed57081700924f901edbf2bbd0cb5b8dc9fda36"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-apple-darwin.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "249a3af6fc3b18b8c02f0c540dbb55be9f95b138"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "58235f31f9f6c91afa6aba6e9b27f026adb2e7f57e42287d949680a171dc4706"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96cf95bb669c130f48392189726a6ec36259a470"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "b39261fbba0e6d698e73daf869eb66605fe430462a2bf5b1c30f3227d0bb788d"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a425897927dee0f3edbc272844892169518bc44d"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "28753069e878a277d9599a02a0340d2066d56a7794f3de49d3d34898e06adc47"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65e9ae1f3979954160393648248b8d07c25351f7"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "2aae5a6f2086f35e43e8456090c47e5940fdc57607e8f0c0776e393a75fdd679"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
git-tree-sha1 = "3e02ca93751554f846163ff477c0afecb4cf5ffc"
os = "freebsd"

    [[protobuf_c.download]]
    sha256 = "11115994cbbf4e13fa38cc198482ba9d52aac70802e8544e9ea16b9dba9da082"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-unknown-freebsd.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2918b81af603308575dd3011aa4d26acfb68b47"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "06a1825474ba6b403dd338c212edf6969cbcea466a384279882a64f970a4e554"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b633c6e04b1a8b92d2ba3bb1f4b472d718798317"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "2790c7915b6387bdaa2c9317157170d63710f564f6dcb017bea3e1f013608c19"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.4.1+0/protobuf_c.v1.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
