[[protobuf_c]]
arch = "aarch64"
git-tree-sha1 = "4223cfd7dd2db8ff1546b379fea6f7ce4556c0c5"
os = "macos"

    [[protobuf_c.download]]
    sha256 = "ac9b7f1ce4ee916b75475277e5f0588d6646e33ccbc7dc56e4e6e962f55fbbb0"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.aarch64-apple-darwin.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02b7e09578ada67d4969985124418c8bd089c535"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "d18ed25fb3955c065dc8ec4f6f51e6029922b142bdeb7b9971d4b02c8ecec685"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cba6c176d16b7e0a3a9aa077e6ee02885a81f6cd"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "6797e567723a7917f8df55647cd851ae19d7c9c0e62d4b6bfb134b440994115b"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7d38b6cea99c3be36f83a6fceaa04c813430949"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "f82f08424e9b8089a1a4a5481a93b1c96f3460b27433aef63fed9fc8e3347e42"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aca3abb83bdd23e42237b09b9163ec0de123fa80"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "741b31cd78a80fa38b107543e9af18eb3187aef7a5b3e1def4a6e6cd9eb29570"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d91bb7fbf479f8b164a4c9e3664cad7d2eb32ab7"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "e6db4b11c2821c5371d370940c57f0083d25d059308c555755cf272c5158a4e9"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d393986a095c0b873430bb6c7acb1eea89f806c"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "12c956a156a22a0d3f07bff6e0d0837877cd09fd998d3b0eac3a95bbf8f4c1f8"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "879412561c61000174e9f11e1e5413c9c6dcb481"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "ef137311550927a5307aaa08eb4c97c7d5205c238149726575517b8075057e60"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c359fc3a49397fe96755dac80fab5e2f24c92166"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "30b89e49fdc51d7f6391b766191a0a2cb2fc52ff0603e27d8633ed0a0df88dd4"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3ed680f6d4f54df2a16090222e0540220be0d3b"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "ceabcb0f96a716ac9fb5153be91030110a66d3a789237efba9c7bb1e9596211a"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44a0f0f02dfa5ccd3f62485e34867286dfc568e0"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "4d476afe9fafdb77f520e2d3a0703e82c153ab3b77f80ae680cd00bbdf037e5d"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e5a1f1bb836971d7c85a0251e429c1451372af8"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "ef46633b49ebef4f8cf980f99c69421e998ccc07ed34ea47181b7ef74c28e147"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[protobuf_c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb598940d783725b69f0fa2e75ccaf10a0b31688"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "b34cb19246cbe66d7caae728688930562be94f97e999f67597373aa0115aafe8"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7587789c736c9c1eafe03c768d621625a78ea2ee"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "7e5fdd3eede06bd7738bcef6e941af02e281f52a34382e266bd515de99b2d3db"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "876d1b77e4d73ae5fae9122d750b3d18dcebde19"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "4303c02a98c3648d85a8f5e7606927091c562838db365afe74252175c1d40543"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39f365f52936945ea983dc8c30159b2734612869"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "3047f685c69df9e8b2743cab6a34f3225d35b2211b79a65421618c5122475344"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a04fc2beefdbb56e7ce2cb03df18f6eec8c307a3"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "52b731ce73c966b8baf53ab278a1e8ffb874218387d6dc7540e612011fc590f7"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12e7c295089932cde51cc682217ab1c5de2d1132"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "f8487783193c0be3eec8153cd15c06d458358ae41e73bb82fddc20751cd2f5ce"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[protobuf_c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35baee192edfbcec543e71ec20318088f4362b2c"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "2f7a57b245f1db60539bcca349413cb7334df43e63986f5d005660cee0b6487a"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[protobuf_c]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "111d5aad020ec589105e13be40ce612750f4b6ee"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "4c5e9384f5599f488c39095e44e7b9d3cc5726f0037e54a6781d2c59f0e284e2"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d9af8b04713a4ac38df0f5f622bdd384885ec6e"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "32533d8c2ed3030d3169eadcd025c8d6e70cc03a90bae343646801c3954261c3"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
git-tree-sha1 = "f48a2e2c442ab0cd415641a4e1fc66e764d24838"
os = "macos"

    [[protobuf_c.download]]
    sha256 = "ad03482d347f9f99a8052293ebac06e452c514514dbd8a70f199489f2bdbd09e"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-apple-darwin.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f63b1d0d78ebf44b879e6554ba9489428b61240e"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "35813e5f5648ca786a021836dbb65ffce19cba37ea25a1adaa78ec7c512fc1bf"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32ebe089295ca16ea8722b3edeb91f212d0a7c11"
libc = "glibc"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "14642229fb6373ad2c7c45b39210e6b3e5df85f241cb5984320fb0fbeef97b53"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2c7997797cbb96246ca1eeb6adb54fba8607c75"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "4f3218ee3d6bcf70cb47feec2235b53b993edb0864fd47b2db8df2d7114ecbd1"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84178953fbaeb1b9a38d71596cbe77704f8c8bea"
libc = "musl"
os = "linux"

    [[protobuf_c.download]]
    sha256 = "d2140d4066830b512ff1015d0ec7a93d3107cfce9596b1b5b9a8378b7141ae0e"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[protobuf_c]]
arch = "x86_64"
git-tree-sha1 = "f69bb482e59ed48ef5bfdb60f6d9ac592aae0f7a"
os = "freebsd"

    [[protobuf_c.download]]
    sha256 = "b0e623189bc87a0854ff56d7fae95975e80be5dbaded46d3183c1d9d61f27988"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-unknown-freebsd.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbba0a884672961be5b1fd7b0feebed20430bc5b"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "4fc4d58265011350f8669498f719e200da14a7bf3a017e0d2b861fb155808a96"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[protobuf_c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab7e7e1fa9d001ce6273e06a1e964060958b8dc7"
os = "windows"

    [[protobuf_c.download]]
    sha256 = "c5971edb74a1b6bbd6a0cddbbdbbe8d7c3adb2ab1116f98850982886bf3d4392"
    url = "https://github.com/JuliaBinaryWrappers/protobuf_c_jll.jl/releases/download/protobuf_c-v1.5.0+0/protobuf_c.v1.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
